app:
  datasource:
    credentials:
      url: jdbc:mysql://${MYSQL_HOSTNAME}:${MYSQL_PORT}/library_users_credentials
      driverClassName: classpath:/mysql-connector-j-8.1.0.jar
      username: admin
      password: secret
    details:
      url: jdbc:mysql://${MYSQL_HOSTNAME}:${MYSQL_PORT}/library_data
      driverClassName: classpath:/mysql-connector-j-8.1.0.jar
      username: admin
      password: secret


server:
  port: 9000
gg:
  jte:
    developmentMode: true
