app:
  datasource:
    credentials:
      url: jdbc:mysql://${MYSQL_HOSTNAME}:${MYSQL_PORT}/library_users_credentials
      driverClassName: com.mysql.cj.jdbc.Driver
      username: admin
      password: secret
    details:
      url: jdbc:mysql://${MYSQL_HOSTNAME}:${MYSQL_PORT}/library_data
      driverClassName: com.mysql.cj.jdbc.Driver
      username: admin
      password: secret
  clients:
    adminHostname: ${ADMIN_HOSTNAME}
    adminPort: ${ADMIN_PORT}


server:
  port: ${AUTH_PORT}
gg:
  jte:
    developmentMode: true
