app:
  datasource:
    credentials:
      url: jdbc:mysql://localhost:3306/library_users_credentials
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: secret
    details:
      url: jdbc:mysql://localhost:3306/library_data
      driverClassName: com.mysql.cj.jdbc.Driver
      username: admin
      password: secret


server:
  port: 9000
gg:
  jte:
    developmentMode: true
